config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'

  resources :companies
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :people, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:index, :new, :create]

  def new
    @company = Company.new
  end

  def index
    @companies = Company.all
  end

  def show
  end

  def create
   @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: 'Company Created!' 
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @company.save
      redirect_to @company
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = 'Company Deleted'
    redirect_to companies_path
  end

  private

  def company_params
    params.require(:company).permit(:name, :location, :employee)
  end

  def set_company
     @company = Company.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
  end

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/companies/index.html.erb
<h1> Company List </h1>
<hr />

<% if @companies.any? %>

<% @companies.each do |list| %>
   <p><%= list.name %></p>
    <p><%= list.location %></p>
    <% end %>
<% else %>
  <h3>No Companies, Please Add One!</h3>
<% end %>
<%= link_to 'Add Company', new_company_path, class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<h1> New Company </h1>
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
  <% end %>

app/views/companies/show.html.erb
    <h1><%= @company.name %></h1>
    <hr />
    <h3><%= @company.location %></h3>
    <%= link_to 'Back to index', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>People#index</h1>
<p>Find me in app/views/people/index.html.erb</p>

app/views/people/new.html.erb
<h1>People#new</h1>
<p>Find me in app/views/people/new.html.erb</p>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>